apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${APP}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ${APP}
        version: ${VER}
    spec:
        containers:
        - name: ${APP}
          env:
          - name: ENV
            value: ${ENV}
#           name: JAVA_OPTS
#      	    value: -javaagent:/opt/newrelic/newrelic.jar 
#              -Dnewrelic.enable.java.8 -Dnewrelic.environment=${ENV}-${APP}
#        	  -XX:-OmitStackTraceInFastThrow -Xms${JVMMIN} -Xmx${JVMMAX} -XX:MaxMetaspaceSize=116m
#        	  -XX:-PrintGCDetails -XX:-PrintGCTimeStamps
          imagePullPolicy: Always
          image: gcr.io/porch-gcp/${APP}:${VER}
          livenessProbe:
              httpGet:
                  path: /ping
                  port: ${PORT}
                  scheme: HTTP
              initialDelaySeconds: 10 # Wait ten seconds for the app before starting livesness checks
              failureThreshold: 3 # 30 seconds of consecutive failures are permitted
              periodSeconds: 10 # Check every ten seconds
              timeoutSeconds: 1 # One second per check to respond
#          readinessProbe:
#              httpGet:
#                  path: /ready
#                  port: ${PORT} # or ${ALTPORT}
#                  scheme: HTTP
#              initialDelaySeconds: 12
#              failureThreshold: 1
#              periodSeconds: 10
#              timeoutSeconds: 1
          resources:
            requests:
              memory: 384Mi
            limits:
              memory: 640Mi
#        terminationGracePeriodSeconds: 30  # Delay before force-killing the pod if app doesn't die

